### ISSUE TITLE
Error pas paràmetre des del server.py

### ISSUE THREAD

**Issue by JnxF** [jordi-petit/lp-moogle-2018#3]
https://github.com/jordi-petit/lp-moogle-2018/blob/a9f36586a9b56768a649f32e495038d662fa03e0/server.py#L24

Hem estat mirant amb l'Albert i la funció no va bé perquè es carrega les llistes i les tuples. Una possible solució és
```python
@app.route("/search")
def search():
    """Returns the results page."""
    try:
        # Tries to read the input as a list or as a tuple
        query = ast.literal_eval(request.args.get("query", ""))
    except:
        # If it fails, try now as it was a string (append quotes)
        try:
            query = ast.literal_eval('"' + request.args.get("query", "") + '"')
        except:
            return render_template("index.html")
        
    results = moogle.answer(app.db, query)
    return render_template("search.html", authors=moogle.authors(), query=query, results=results)

**Comment by jordi-petit** [comment]
:+1, gràcies per apuntar-ho! De fet el mateix error és a answer.py. Ho he corregit als dos fent que aquesta feina l'hagi de fer la funció` answer()`de `moogle.py` que reb l'string i prou.
